import re
from pathlib import Path
from typing import Dict, Any, List, Optional

from .base_module import BaseModule

class KnifeDamageModule(BaseModule):
    """Модуль для увеличения урона ножа"""
    
    def __init__(self):
        super().__init__()
        self.display_name = "Knife Damage Modifier"
        self.files = {
            'ObjPrototypes.cfg': 'ObjPrototypes.cfg'
        }
        # Кэш для базового урона
        self._base_damage_cache = None
    
    def get_predefined_configs(self) -> List[Dict[str, Any]]:
        """Предустановленные множители урона"""
        return [
            {'name': '2x Damage', 'config': {'multiplier': 2.0}},
            {'name': '3x Damage', 'config': {'multiplier': 3.0}},
            {'name': '5x Damage', 'config': {'multiplier': 5.0}},
            {'name': '10x Damage', 'config': {'multiplier': 10.0}},
        ]
    
    def get_custom_config(self) -> Optional[Dict[str, Any]]:
        """Пользовательский ввод множителя"""
        print("\nCustom Knife Damage Configuration")
        print("=" * 40)
        print("Higher multiplier = more damage")
        print("2.0 = double damage, 5.0 = five times damage")
        
        try:
            multiplier = float(input("Damage multiplier (1.01-100.0): ").strip())
            if not 1.01 <= multiplier <= 100.0:
                print("Multiplier must be between 1.01 and 100.0")
                return None
            return {'multiplier': multiplier}
        except ValueError:
            print("Invalid input")
            return None
    
    def _get_base_knife_damage(self) -> Optional[float]:
        """Извлекает базовый урон ножа из распакованных файлов"""
        # Используем кэш, чтобы не искать каждый раз
        if self._base_damage_cache is not None:
            return self._base_damage_cache
        
        # Ищем файл с прототипами оружия
        source_file = self.find_file_in_extraction("ObjPrototypes.cfg")
        if not source_file:
            # Может быть бинарный
            source_file = self.find_file_in_extraction("ObjPrototypes.cfg.bin")
            if source_file:
                print("⚠ Original ObjPrototypes is binary, cannot read base damage. Using fallback value.")
                # Возвращаем стандартное значение из игры (примерно 50)
                return 50.0
            return None
        
        # Читаем текстовый файл
        try:
            with open(source_file, 'r', encoding='utf-8', errors='ignore') as f:
                content = f.read()
            
            # Ищем секцию Knife
            # Шаблон: Knife : struct.begin { ... BaseDamage = ... ... }
            pattern = r'Knife\s*:\s*struct\.begin.*?BaseDamage\s*=\s*([\d.]+)'
            match = re.search(pattern, content, re.DOTALL | re.IGNORECASE)
            if match:
                damage = float(match.group(1))
                self._base_damage_cache = damage
                print(f"Found base knife damage: {damage}")
                return damage
            
            # Альтернативный поиск
            pattern2 = r'BaseDamage\s*=\s*([\d.]+)'
            matches = re.findall(pattern2, content)
            if matches:
                # Примерно предположим, что первый найденный - для ножа (не точно)
                damage = float(matches[0])
                self._base_damage_cache = damage
                print(f"Found potential base knife damage: {damage}")
                return damage
            
            print("⚠ Could not find BaseDamage in ObjPrototypes.cfg")
            return None
        except Exception as e:
            print(f"Error reading ObjPrototypes.cfg: {e}")
            return None
    
    def apply_configuration(self, config: Dict[str, Any], output_path: Path) -> bool:
        """Применяет множитель урона к ножу"""
        try:
            game_data_path = output_path / "Stalker2/Content/GameLite/GameData"
            game_data_path.mkdir(parents=True, exist_ok=True)
            
            multiplier = config['multiplier']
            
            # Получаем базовый урон
            base_damage = self._get_base_knife_damage()
            if base_damage is None:
                # Если не нашли, используем разумное значение по умолчанию (50)
                base_damage = 50.0
                print(f"Using default base damage: {base_damage}")
            
            new_damage = base_damage * multiplier
            new_damage = round(new_damage, 2)
            
            print(f"Base damage: {base_damage}, multiplier: {multiplier}, new damage: {new_damage}")
            
            # Создаём файл-оверрайд
            output_file = game_data_path / "KnifeDamageOverride.cfg"
            
            # Используем refurl для ссылки на оригинальный прототип
            content = f"""; Knife Damage Override
; Generated by S.T.A.L.K.E.R. 2 Mod Builder

KnifeDamageOverride : struct.begin {{refurl=../ObjPrototypes.cfg;refkey=Knife}}
    BaseDamage = {new_damage}
struct.end
"""
            with open(output_file, 'w', encoding='utf-8') as f:
                f.write(content)
            
            print(f"✓ Created {output_file} with new damage: {new_damage}")
            return True
            
        except Exception as e:
            print(f"Error applying knife damage configuration: {e}")
            return False