import re
from pathlib import Path
from typing import Dict, Any, List, Optional

from .base_module import BaseModule, _   # <-- добавили импорт _

class TraderDurabilityModule(BaseModule):
    
    def __init__(self):
        super().__init__()
        self.display_name = "Traders Buy Broken Stuff"
    
    def get_predefined_configs(self) -> List[Dict[str, Any]]:
        return [
            {'name': _('Accept All (0% minimum)'), 'config': {'min_durability': 0.0}},
            {'name': _('Accept Damaged (25% minimum)'), 'config': {'min_durability': 0.25}},
            {'name': _('Accept Used (50% minimum)'), 'config': {'min_durability': 0.50}},
            {'name': _('Vanilla (70% minimum)'), 'config': {'min_durability': 0.70}},
        ]
    
    def get_custom_config(self) -> Optional[Dict[str, Any]]:
        print("\n" + _("Custom Trader Durability Requirements"))
        print("=" * 40)
        print(_("Set minimum item condition traders will accept"))
        print(_("0% = Accept completely broken items"))
        print(_("100% = Only accept pristine items"))
        
        try:
            percentage = int(input(_("Minimum durability (0-100%): ")).strip())
            if not 0 <= percentage <= 100:
                print(_("Percentage must be between 0 and 100"))
                return None
            return {'min_durability': percentage / 100.0}
        except ValueError:
            print(_("Invalid input"))
            return None
    
    def apply_configuration(self, config: Dict[str, Any], output_path: Path) -> bool:
        try:
            game_data_path = output_path / "Stalker2/Content/GameLite/GameData"
            game_data_path.mkdir(parents=True, exist_ok=True)
            
            # Ищем оригинальный файл (текстовый или бинарный)
            source_file = self.find_file_in_extraction("TradePrototypes.cfg")
            if not source_file:
                source_file = self.find_file_in_extraction("TradePrototypes.cfg.bin")
            
            if not source_file:
                print(_("TradePrototypes.cfg not found in extraction"))
                return False
            
            output_file = game_data_path / "TradeDurabilityOverride.cfg"
            min_durability = config['min_durability']
            formatted_value = f"{min_durability:.2f}".rstrip('0').rstrip('.') + 'f'
            
            content = f"""; Trader durability override
; Generated by S.T.A.L.K.E.R. 2 Mod Builder

[TraderDurabilityOverride] : struct.begin {{refurl=../TradePrototypes.cfg}}
    WeaponSellMinDurability = {formatted_value}
    ArmorSellMinDurability = {formatted_value}
struct.end
"""
            with open(output_file, 'w', encoding='utf-8') as f:
                f.write(content)
            
            print(f"✓ {_('Created override file with min durability = {:.0%}').format(min_durability)}")
            return True
            
        except Exception as e:
            print(f"{_('Error applying configuration')}: {e}")
            return False