import re
from pathlib import Path
from typing import Dict, Any, List, Optional

from .base_module import BaseModule, _

class WeaponDurabilityModule(BaseModule):
    
    def __init__(self):
        super().__init__()
        self.display_name = "Weapon Durability Modifier"
    
    def get_predefined_configs(self) -> List[Dict[str, Any]]:
        return [
            {'name': _('2x More Durable'), 'config': {'reduction_factor': 2.0}},
            {'name': _('3x More Durable'), 'config': {'reduction_factor': 3.0}},
            {'name': _('5x More Durable'), 'config': {'reduction_factor': 5.0}},
            {'name': _('10x More Durable'), 'config': {'reduction_factor': 10.0}},
        ]
    
    def get_custom_config(self) -> Optional[Dict[str, Any]]:
        print("\n" + _("Custom Weapon Durability Configuration"))
        print("=" * 40)
        print(_("Higher factor = weapons degrade slower"))
        print(_("2.0 = weapons last twice as long"))
        
        try:
            factor = float(input(_("Durability factor (1.01-10.0): ")).strip())
            if not 1.01 <= factor <= 10.0:
                print(_("Factor must be between 1.01 and 10.0"))
                return None
            return {'reduction_factor': factor}
        except ValueError:
            print(_("Invalid input"))
            return None
    
    def apply_configuration(self, config: Dict[str, Any], output_path: Path) -> bool:
        try:
            game_data_path = output_path / "Stalker2/Content/GameLite/GameData"
            game_data_path.mkdir(parents=True, exist_ok=True)
            
            reduction_factor = config['reduction_factor']
            
            # Создаём оверрайд для базового прототипа игрока
            output_file = game_data_path / "WeaponDurabilityOverride.cfg"
            
            # В оригинальном файле (бинарном) параметр называется DurabilityDamagePerShot.
            # Мы создаём структуру, которая переопределит его для всех видов оружия через общий прототип.
            # Используем refurl на PlayerWeaponSettingsPrototypes (даже если он бинарный, ссылка работает).
            content = f"""; Weapon durability override
; Generated by S.T.A.L.K.E.R. 2 Mod Builder

; Переопределяем параметр износа для всех видов оружия
[WeaponDurabilityOverride] : struct.begin {{refurl=../WeaponData/CharacterWeaponSettingsPrototypes/PlayerWeaponSettingsPrototypes.cfg}}
    DurabilityDamagePerShot = 1.0 / {reduction_factor}
struct.end
"""
            with open(output_file, 'w', encoding='utf-8') as f:
                f.write(content)
            
            print(_("✓ Created override file with durability factor = {:.2f}").format(reduction_factor))
            return True
            
        except Exception as e:
            print(_("Error applying configuration: {}").format(e))
            return False